// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOJInC2hP_NV6tout6R6OIbY6Fhab8Vb4',
    appId: '1:130235349121:web:52c1c47aa03f9386e9f580',
    messagingSenderId: '130235349121',
    projectId: 'eos-clock-bd538',
    authDomain: 'eos-clock-bd538.firebaseapp.com',
    storageBucket: 'eos-clock-bd538.appspot.com',
    measurementId: 'G-YCVX0ED84F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrFUmM12rrp0Agrs1cXSGZn97bmofACnU',
    appId: '1:130235349121:android:76e4bceda0915960e9f580',
    messagingSenderId: '130235349121',
    projectId: 'eos-clock-bd538',
    storageBucket: 'eos-clock-bd538.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDRSp3X-Qt7Rtq-Hc66NogiCrEf6hlXY',
    appId: '1:130235349121:ios:564e5722a0a00de0e9f580',
    messagingSenderId: '130235349121',
    projectId: 'eos-clock-bd538',
    storageBucket: 'eos-clock-bd538.appspot.com',
    iosClientId: '130235349121-d56ivecb8jpgpgfvcl9pp51l8mhqdeej.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPractice',
  );
}
